version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 40
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.9
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.9
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.10.4
    - 7.12.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@types/express"
    versions:
    - 4.17.9
  - dependency-name: concurrently
    versions:
    - 5.3.0
  - dependency-name: supertest
    versions:
    - 6.0.1
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.7
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.15
  - dependency-name: helmet
    versions:
    - 4.1.1
  - dependency-name: typescript
    versions:
    - 4.0.2
  - dependency-name: "@types/morgan"
    versions:
    - 1.9.1
  - dependency-name: ts-jest
    versions:
    - 24.3.0
